name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout the code
    - uses: actions/checkout@v4

    # Step 2: Log in to GitHub Container Registry (GHCR)
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # Step 3: Get the short commit hash
    - name: Get short commit hash
      id: vars
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    # Step 4: Build the Docker image
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}/django-cicd:${{ env.SHORT_SHA }}

    # Step 5: Push the Docker image to GHCR
    - name: Push the Docker image
      run: docker push ghcr.io/${{ github.repository }}/django-cicd:${{ env.SHORT_SHA }}
